name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline script
        run: |
          node -v
          npm -v
      - name: Python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: current directory in powershell
        run: Get-Location
      - name: current directory in bash
        run: pwd
        shell: bash